[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
drift-stake-voter = "H5cjESgwpXoTf7szHBch17noet6DdTFCrMgHcTro5cLb"

[programs.devnet]
drift-stake-voter = "H5cjESgwpXoTf7szHBch17noet6DdTFCrMgHcTro5cLb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
